server:
  port: 8889
spring:
  application:
    name: config-client
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true               # клиент упадёт, если сервер недоступен
  profiles:
    active: dev                     # профиль, который будет запрошен
#eureka:
#  client:
#    enabled: true
#    healthcheck:
#      enabled: true
#    service-url:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    lease-renewal-interval-in-seconds: 35
#    prefer-ip-address: true
#    ip-address: 127.0.0.1
#    instance-id: ${spring.application.name}:${random.uuid}
