server:
  port: 8890
spring:
  application:
    name: client-service
eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}